### ISSUE TITLE
Add learning content from the "Productivity SRG"

### ISSUE THREAD

**Issue by UPstartDeveloper** [Pondorasti/makeschool#24]
Hey gang,

Looking for a place to host all the previous meeting agendas we have from the "Productivity SRG" so that the learning content can still benefit folks - could we maybe link [this](https://drive.google.com/drive/folders/1WIK9-rvC5Q3tOXpBQ_jiuwUprumoCcow?usp=sharing) somewhere along the site footer for now? 

At the moment the link just goes to my GDrive. In the future, I plan to place it somewhere that'll be more presentable, e.g. a series of posts on my Medium blog.

**Comment by pondorasti** [comment]
@UPstartDeveloper  I will make a copy of those documents and upload it to the makeschoolfail GDrive. Do you have more of those things we could add? I could potentially create sections in the footer similar to this UI:

<img width="1110" alt="Screenshot 2021-07-24 at 14 10 13" src="https://user-images.githubusercontent.com/32957606/126881137-2eb7ddde-2651-4b21-9780-b8bfe0fd2a3d.png">

**Comment by UPstartDeveloper** [comment]
Nope, that's it @Pondorasti
thanks!

**Comment by chrismlee26** [comment]
Add Internship//Job Readiness & Product Manager Rubrics
https://docs.google.com/document/d/17zL8KRh2KHIV1jySOYU3kiDUY9RYOZDYbJGVZLeUghE/edit?usp=sharing
https://docs.google.com/document/d/12HN0dHVDkgroVqaHNRee9QGxUDvnrcipAFBZwszIePQ/edit?usp=sharing

**Comment by pondorasti** [comment]
Considering the lack of categories in our footer and for the sake of simplicity I will add a GDrive hyperlink to the footer that points to a public google folder with all miscellaneous resources.
